# Generated by Django 5.1.6 on 2025-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_limit",
            field=models.IntegerField(default=5),
        ),
    ]
